const express=require('express')
const path=require('path')
let cors=require('cors')
const app=express()
const sequelize=require('./util/database')
const user=require('./models/user')
const userRoutes=require('./routes/user')
const dotenv=require('dotenv')
dotenv.config()
app.use(cors())
app.use(express.json())
app.use('/user',userRoutes)
sequelize.sync().then(()=>{
    app.listen(3000)
}).catch(err=>console.log(err))